# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html>
<html lang=\"en\">

<head>
    <meta charset=\"UTF-8\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />
    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\" />
    <title>Slot Car Data Logger</title>
    <link rel=\"stylesheet\" href=\"static/index.css\" />
    <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"static/apple-touch-icon.png\">
    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"static/favicon-32x32.png\">
    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"static/favicon-16x16.png\">
    <!-- <link rel=\"manifest\" href=\"/site.webmanifest\"> -->
    <!--
    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.0/chart.min.js\"></script>
    -->
    <script src=\"https://cdn.jsdelivr.net/npm/chart.js@3.3.2\"></script>
    <script src=\"https://cdn.jsdelivr.net/npm/luxon@1.27.0\"></script>
    <script src=\"https://cdn.jsdelivr.net/npm/chartjs-adapter-luxon@1.0.0\"></script>
    <script src=\"https://cdn.jsdelivr.net/npm/chartjs-plugin-streaming@2.0.0\"></script>
    <script type=\"text/javascript\">
        function loadCanvas(id, canvas) """
    yield """{
            var canvas = document.createElement(canvas);
            console.log("""
    yield """{canvas})
            div = document.getElementById(id);
            console.log("""
    yield """{div})
            canvas.id     = canvas;
            canvas.width  = '100%';
            canvas.height = '100%';
            canvas.style.zIndex   = 8;
            canvas.style.position = \"absolute\";
            canvas.style.border   = \"1px solid\";
            div.appendChild(canvas);
            return canvas;
        }
        function doCanvas() """
    yield """{
            const canvas = document.getElementById(\"chart1\");
            console.log("""
    yield """{canvas})
            fitToContainer(canvas);
            const ctx = canvas.getContext(\"2d\");
            ctx.fillStyle = \"#00FF00\";
            ctx.fillRect(0, 0, canvas.width, canvas.height);
            canvas3 = loadCanvas('div3', 'canvas3')
            console.log("""
    yield """{canvas3})
            fitToContainer(canvas3);
        }

        function fitToContainer(canvas)"""
    yield """{
          // Make it visually fill the positioned parent
          canvas.style.width = '100%';
          canvas.style.height = '100%';
          // ...then set the internal size to match
          canvas.width  = canvas.offsetWidth;
          canvas.height = canvas.offsetHeight;
        }

        function createDiv(id, aclass = 'mydiv', style = 'background-color: grey', width = '100%', height = '100%', float = 'left') """
    yield """{
            console.log("""
    yield """{id})
            console.log("""
    yield """{aclass})
            console.log("""
    yield """{style})
            console.log("""
    yield """{width})
            console.log("""
    yield """{height})
            console.log("""
    yield """{float})
            var iDiv = document.createElement('div');
            iDiv.id = id;
            iDiv.className = aclass;
            iDiv.style = style;
            iDiv.style.width = width;
            iDiv.style.height = height;
            iDiv.style.float = float;
            document.body.appendChild(iDiv);
            return iDiv;
        }

        function createAppendDiv(div, id, aclass, style, width, height, float) """
    yield """{
            iDiv = createDiv(id, aclass, style, width, height, float);
            div.appendChild(iDiv);
        }

        function getll() """
    yield """{
            return navigator.geolocation.getCurrentPosition(function (p) """
    yield """{return p.coords.latitude, p.coords.longitude});
        }

        function dividePage(elements = 1) """
    yield """{
            // tell it a grid and how to lay it out e.g. 1, 2 x 2, odd/even, 3 x 3, 4 x 4
            console.log(getll())
            myGeoLocation()
            //console.log("""
    yield """{elements})
            ct = document.getElementsByClassName(\"mydiv\").length
            //console.log('Count ', ct)
            if (elements == 1) """
    yield """{
                createDiv('id1')
            } else if (elements == 2) """
    yield """{
                console.log('2 splits')
                createDiv('id1', aclass = 'mydiv', style = 'background-color: grey', width = '100%', height = '50%', float = 'left');
                createDiv('id2', aclass = 'mydiv', style = 'background-color: orange', width = '100%', height = '50%', float = 'left')
            } else if (elements == 3) """
    yield """{
                createDiv('id1', aclass = 'mydiv', style = 'background-color: grey', width = '100%', height = '50%', float = 'left');
                div20 = createDiv('id20', aclass = 'mydiv', style = 'background-color: grey', width = '100%', height = '50%', float = 'left')
                createAppendDiv(div20, 'id2', aclass = 'mydiv', style = 'background-color: orange', width = '50%', height = '100%', float = 'left')
                createAppendDiv(div20, 'id3', aclass = 'mydiv', style = 'background-color: green', width = '50%', height = '100%', float = 'left')
            } else if (elements == 4) """
    yield """{
                div10 = createDiv('id10', aclass = 'mydiv', style = 'background-color: white', width = '100%', height = '50%', float = 'left');
                createAppendDiv(div10, 'id1', aclass = 'mydiv', style = 'background-color: orange', width = '50%', height = '100%', float = 'left')
                createAppendDiv(div10, 'id2', aclass = 'mydiv', style = 'background-color: green', width = '50%', height = '100%', float = 'left')
                div20 = createDiv('id20', aclass = 'mydiv', style = 'background-color: black', width = '100%', height = '50%', float = 'left')
                createAppendDiv(div20, 'id3', aclass = 'mydiv', style = 'background-color: red', width = '50%', height = '100%', float = 'left')
                createAppendDiv(div20, 'id4', aclass = 'mydiv', style = 'background-color: blue', width = '50%', height = '100%', float = 'left')
            } else if (elements == 5) """
    yield """{
                div10 = createDiv('id10', aclass = 'mydiv', style = 'background-color: white', width = '100%', height = '50%', float = 'left');
                createAppendDiv(div10, 'id1', aclass = 'mydiv', style = 'background-color: orange', width = '50%', height = '100%', float = 'left')
                createAppendDiv(div10, 'id2', aclass = 'mydiv', style = 'background-color: green', width = '50%', height = '100%', float = 'left')
                div20 = createDiv('id20', aclass = 'mydiv', style = 'background-color: black', width = '100%', height = '50%', float = 'left')
                createAppendDiv(div20, 'id3', aclass = 'mydiv', style = 'background-color: red', width = '50%', height = '100%', float = 'left')
                createAppendDiv(div20, 'id4', aclass = 'mydiv', style = 'background-color: blue', width = '50%', height = '100%', float = 'left')
            }
            ct = document.getElementsByClassName(\"mydiv\").length
            console.log('Count ', ct)
        }

        const theGeoLocation = """
    yield """{ lat: '', long: '' };

        function goodGeo(position) """
    yield """{
            const latitude = position.coords.latitude;
            const longitude = position.coords.longitude;
            const aurl = `https://www.openstreetmap.org/#map=18/$"""
    yield """{latitude}/$"""
    yield """{longitude}`;
            // mapLink.textContent = `Latitude: $"""
    yield """{latitude} °, Longitude: $"""
    yield """{longitude} °`;
            theGeoLocation.lat = latitude
            theGeoLocation.long = longitude
            console.log(theGeoLocation)
            window.open(aurl, '_blank').focus();
        }

        function badGeo() """
    yield """{
            console.log(\"Unable to retrieve your location\");
        }

        function myGeoLocation() """
    yield """{
             if (!navigator.geolocation) """
    yield """{
                console.log(\"Geolocation is not supported by your browser\");
             } else """
    yield """{
                status.textContent = \"Locating…\";
                navigator.geolocation.getCurrentPosition(goodGeo, badGeo);
             }
        }
</script>

</head>

<body>
    <h1>Slot Car Data Logger</h1>
    <script>dividePage(elements = 4)</script>
    <!--
    read the current geo location
    read track database based on geo
    load track
    read number of lanes
    grid the page based on number of lanes

    <script src=\"static/index.js\"></script>

    <div id='div1' style=\"background-color: blue; width: 100%; height: 650px;\">
        <div id='div2' style=\"background-color: red; width: 50%; height: 550px; float:left;\">
This is the first division to have a vertical alignment.
            <canvas id=\"chart1\" width=\"100%\" height=\"100%\"></canvas>
        </div>
        <div id='div3' style=\"background-color: yellow; width:50%; height: 550px; float:left;\">
This is the second division to have a vertical alignment.
        </div>
    </div>
<script>doCanvas()</script>
-->
</body>

</html>
"""
